Fix. yet again.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -600,7 +600,7 @@ done
 [ -f Makefile  ] && rm Makefile
 set -e 
 if [ "$_arg_double" = "on" ];then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double"; else _CFLAGS+=" -DSPFLOAT=float";fi
-$_arg_cc -Iinclude $_arg_soundpipe_inc -DDEBUG $_arg_cflags $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; return 1;)
+$_arg_cc -Iinclude $_arg_soundpipe_inc -DDEBUG $_arg_cflags $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)
 echo generate header
 ./util/generate_header || exit 1
 echo generate parser
