configure now checks default driver.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -605,6 +605,8 @@ done
 ### END OF CODE GENERATED BY Argbash (sortof) ### ])
 # [ <-- needed because of Argbash
 [ -f Makefile  ] && rm Makefile
+VALID_DRIVER=" dummy spa sndfile alsa jack portaudio soundio"
+grep "$_arg_d_func" <<<  "$VALID_DRIVER" || { echo "invalid default driver";exit 1; }
 set -e 
 if [ "$_arg_double" = "on" ]; then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
 if [ "$_arg_double" = "1"  ];then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
