Clean (a bit) build system.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -50,7 +50,7 @@
 # ARG_HELP([The general script's help msg])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.3.0 one line above ###
+### START OF CODE GENERATED BY Argbash v2.4.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
@@ -62,6 +62,16 @@ die()
 	echo "$1" >&2
 	exit ${_ret}
 }
+
+begins_with_short_option()
+{
+	local first_option all_short_options
+	all_short_options='h'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+
 
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 : "${PRG:="gwion"}"
@@ -575,7 +585,7 @@ do
 			_arg_debug_stack="on"
 			test "${1:0:5}" = "--no-" && _arg_debug_stack="off"
 			;;
-		-h|--help)
+		-h*|--help)
 			print_help
 			exit 0
 			;;
@@ -605,135 +615,154 @@ if [ "$_arg_double" = "1"  ];then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
 if [ "$USE_COVERAGE" = "1"  ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
 if [ "$USE_COVERAGE" = "on" ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
 if [ "$_arg_soundpipe_inc" ]; then _CFLAGS+=" $_arg_soundpipe_inc";fi
-$_arg_cc -Iinclude -DDEBUG $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)
+cmd="$_arg_cc -Iinclude -DDEBUG $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header"
+eval "$cmd" || (echo 'invalid compilation options'; exit 1;)
 ./util/generate_header || exit 1
-{
-echo "PRG ?= ${_arg_prg}"
-echo "CC ?= ${_arg_cc}"
-echo "YACC ?= ${_arg_yacc}"
-echo "LEX ?= ${_arg_lex}"
-echo "PREFIX ?= ${_arg_prefix}"
-echo "SOUNDPIPE_LIB ?= ${_arg_soundpipe_lib}"
-echo "SOUNDPIPE_INC ?= ${_arg_soundpipe_inc}"
-} >> Makefile
 
-cat <<-  EOF >> Makefile
-
+# handle base options
+printf "\n# handle base options\n" >> Makefile
+for iter in prg cc yacc lex prefix soundpipe_lib soundpipe_inc
+do
+	arg="_arg_${iter}"
+	echo "${iter~~} ?= ${!arg}"
+done >> Makefile
+ echo -e "
 # base flags
 LDFLAGS += -lm -ldl -rdynamic -lpthread
 CFLAGS += -Iinclude -std=c99 -O3 -mfpmath=sse -mtune=native -fno-strict-aliasing -Wall -pedantic -D_GNU_SOURCE
-EOF
+" >> Makefile
+
 # handle boolean options
-echo -e "\n# handle boolean options" >> Makefile
-echo "USE_DOUBLE  = $_arg_double" >> Makefile
-echo "USE_COVERAGE ?= $_arg_coverage" >> Makefile
-echo "USE_MEMCHECK ?= $_arg_memcheck" >> Makefile
+printf "\n# handle boolean options\n" >> Makefile
+for iter in double coverage memcheck
+do
+	arg="_arg_$iter"
+	if [ "$iter" = "double" ]
+	then echo "USE_${iter~~}  = ${!arg}"
+	else echo "USE_${iter~~} ?= ${!arg}"
+	fi
+done >> Makefile
+
 # handle definitions
-echo -e "\n# handle definitions" >> Makefile
-echo "D_FUNC ?= ${_arg_d_func}_driver" >> Makefile
+printf "\n# handle definitions\n" >> Makefile
+d_func=d_func
+for iter in $d_func
+
+do
+	arg="_arg_${iter}"
+	echo "${iter~~} ?= ${!arg}_driver"
+done >> Makefile
+
 # handle directories
-echo -e "\n# handle directories" >> Makefile
-echo "GWION_API_DIR ?= \${PREFIX}/lib/Gwion/api" >> Makefile
-echo "GWION_DOC_DIR ?= \${PREFIX}/lib/Gwion/doc" >> Makefile
-echo "GWION_TAG_DIR ?= \${PREFIX}/lib/Gwion/tag" >> Makefile
-echo "GWION_TOK_DIR ?= \${PREFIX}/lib/Gwion/tok" >> Makefile
-echo "GWION_ADD_DIR ?= \${PREFIX}/lib/Gwion/add" >> Makefile
+printf "\n# handle directories\n" >> Makefile
+for iter in api:api doc:doc tag:tag tok:tok add:add
+do
+	key=$(echo "$iter" | cut -d ':' -f 1)
+	val=$(echo "$iter" | cut -d ':' -f 2)
+	lib=$(echo "$iter" | cut -d ':' -f 4)
+	echo "GWION_${key~~}_DIR ?= \${PREFIX}/lib/Gwion/${val}"
+done >> Makefile
 # handle libraries
-echo -e "\n# handle libraries" >> Makefile
-echo "DUMMY_D ?= $_arg_dummy" >> Makefile
-echo "SPA_D ?= $_arg_spa" >> Makefile
-echo "SNDFILE_D ?= $_arg_sndfile" >> Makefile
-echo "ALSA_D ?= $_arg_alsa" >> Makefile
-echo "JACK_D ?= $_arg_jack" >> Makefile
-echo "PORTAUDIO_D ?= $_arg_portaudio" >> Makefile
-echo "SOUNDIO_D ?= $_arg_soundio" >> Makefile
+printf "\n# handle libraries\n" >> Makefile
+for iter in dummy spa sndfile alsa jack portaudio soundio
+do
+	arg="_arg_$iter"
+	echo "${iter~~}_D ?= ${!arg}"
+done >> Makefile
+
 # handle debug
-echo -e "\n# handle debug" >> Makefile
-echo "DEBUG_COMPILE ?= $_arg_debug_compile" >> Makefile
-echo "DEBUG_OPERATOR ?= $_arg_debug_operator" >> Makefile
-echo "DEBUG_TYPE ?= $_arg_debug_type" >> Makefile
-echo "DEBUG_SCAN0 ?= $_arg_debug_scan0" >> Makefile
-echo "DEBUG_SCAN1 ?= $_arg_debug_scan1" >> Makefile
-echo "DEBUG_SCAN2 ?= $_arg_debug_scan2" >> Makefile
-echo "DEBUG_EMIT ?= $_arg_debug_emit" >> Makefile
-echo "DEBUG_VM ?= $_arg_debug_vm" >> Makefile
-echo "DEBUG_INSTR ?= $_arg_debug_instr" >> Makefile
-echo "DEBUG_SHREDULER ?= $_arg_debug_shreduler" >> Makefile
-echo "DEBUG_STACK ?= $_arg_debug_stack" >> Makefile
-echo '' >> Makefile
-{
-	echo '# initialize source lists'
-	for tgt in "core" "lang" "ugen" "eval"
-	do echo "${tgt}_src := \$(wildcard ${tgt}/*.c)"
-	done
-	printf "drvr_src := drvr/driver.c\n\n# add libraries\n"
-} >> Makefile
-echo -e "ifeq (\${DUMMY_D}, on)\nCFLAGS += -DHAVE_DUMMY\ndrvr_src += drvr/dummy.c\nelse ifeq (\${DUMMY_D}, 1)\nCFLAGS +=-DHAVE_DUMMY\ndrvr_src +=drvr/dummy.c\nendif\n" >> Makefile
-echo -e "ifeq (\${SPA_D}, on)\nCFLAGS += -DHAVE_SPA\ndrvr_src += drvr/spa.c\nelse ifeq (\${SPA_D}, 1)\nCFLAGS +=-DHAVE_SPA\ndrvr_src +=drvr/spa.c\nendif\n" >> Makefile
-echo -e "ifeq (\${SNDFILE_D}, on)\nLDFLAGS += -lsndfile\nCFLAGS += -DHAVE_SNDFILE\ndrvr_src += drvr/sndfile.c\nelse ifeq (\${SNDFILE_D}, 1)\nLDFLAGS += -lsndfile\nCFLAGS +=-DHAVE_SNDFILE\ndrvr_src +=drvr/sndfile.c\nendif\n" >> Makefile
-echo -e "ifeq (\${ALSA_D}, on)\nLDFLAGS += -lasound\nCFLAGS += -DHAVE_ALSA\ndrvr_src += drvr/alsa.c\nelse ifeq (\${ALSA_D}, 1)\nLDFLAGS += -lasound\nCFLAGS +=-DHAVE_ALSA\ndrvr_src +=drvr/alsa.c\nendif\n" >> Makefile
-echo -e "ifeq (\${JACK_D}, on)\nLDFLAGS += -ljack\nCFLAGS += -DHAVE_JACK\ndrvr_src += drvr/jack.c\nelse ifeq (\${JACK_D}, 1)\nLDFLAGS += -ljack\nCFLAGS +=-DHAVE_JACK\ndrvr_src +=drvr/jack.c\nendif\n" >> Makefile
-echo -e "ifeq (\${PORTAUDIO_D}, on)\nLDFLAGS += -lportaudio\nCFLAGS += -DHAVE_PORTAUDIO\ndrvr_src += drvr/portaudio.c\nelse ifeq (\${PORTAUDIO_D}, 1)\nLDFLAGS += -lportaudio\nCFLAGS +=-DHAVE_PORTAUDIO\ndrvr_src +=drvr/portaudio.c\nendif\n" >> Makefile
-echo -e "ifeq (\${SOUNDIO_D}, on)\nLDFLAGS += -lsoundio\nCFLAGS += -DHAVE_SOUNDIO\ndrvr_src += drvr/soundio.c\nelse ifeq (\${SOUNDIO_D}, 1)\nLDFLAGS += -lsoundio\nCFLAGS +=-DHAVE_SOUNDIO\ndrvr_src +=drvr/soundio.c\nendif\n" >> Makefile
-echo "# add boolean" >> Makefile
-echo -e "ifeq (\${USE_COVERAGE}, on)\nCFLAGS += -ftest-coverage -fprofile-arcs\nendif" >> Makefile
-echo -e "ifeq (\${USE_COVERAGE}, 1)\nCFLAGS += -ftest-coverage -fprofile-arcs\nendif" >> Makefile
-echo -e "ifeq (\${USE_COVERAGE}, on)\nLDFLAGS += --coverage\nendif" >> Makefile
-echo -e "ifeq (\${USE_COVERAGE}, 1)\nLDFLAGS += --coverage\nendif" >> Makefile
-echo -e "ifeq (\${USE_MEMCHECK}, on)\nCFLAGS += -g\nendif" >> Makefile
-echo -e "ifeq (\${USE_MEMCHECK}, 1)\nCFLAGS += -g\nendif" >> Makefile
-echo -e "ifeq (\${USE_DOUBLE}, on)\nCFLAGS += -DUSE_DOUBLE -DSPFLOAT=double\nelse ifeq (\${USE_DOUBLE}, 1)\nCFLAGS +=-DUSE_DOUBLE -DSPFLOAT=double\nelse\nCFLAGS+=-DSPFLOAT=float\nendif\n" >> Makefile
-echo -e "\n# add definitions" >> Makefile
-echo "CFLAGS+= -DD_FUNC=\${D_FUNC}" >> Makefile
-echo -e "\n# add directories" >> Makefile
-printf 'CFLAGS+= -DGWION_API_DIR=\\' >> Makefile
-printf "\"\${GWION_API_DIR}" >> Makefile
-printf '\\"\n' >> Makefile
-printf 'CFLAGS+= -DGWION_DOC_DIR=\\' >> Makefile
-printf "\"\${GWION_DOC_DIR}" >> Makefile
-printf '\\"\n' >> Makefile
-printf 'CFLAGS+= -DGWION_TAG_DIR=\\' >> Makefile
-printf "\"\${GWION_TAG_DIR}" >> Makefile
-printf '\\"\n' >> Makefile
-printf 'CFLAGS+= -DGWION_TOK_DIR=\\' >> Makefile
-printf "\"\${GWION_TOK_DIR}" >> Makefile
-printf '\\"\n' >> Makefile
-printf 'CFLAGS+= -DGWION_ADD_DIR=\\' >> Makefile
-printf "\"\${GWION_ADD_DIR}" >> Makefile
-printf '\\"\n' >> Makefile
-echo -e "\n# add debug flags" >> Makefile
-printf "ifeq (\${DEBUG_COMPILE}, on)\nCFLAGS += -DDEBUG_COMPILE\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_COMPILE}, 1)\nCFLAGS += -DDEBUG_COMPILE\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_OPERATOR}, on)\nCFLAGS += -DDEBUG_OPERATOR\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_OPERATOR}, 1)\nCFLAGS += -DDEBUG_OPERATOR\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_TYPE}, on)\nCFLAGS += -DDEBUG_TYPE\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_TYPE}, 1)\nCFLAGS += -DDEBUG_TYPE\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_SCAN0}, on)\nCFLAGS += -DDEBUG_SCAN0\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_SCAN0}, 1)\nCFLAGS += -DDEBUG_SCAN0\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_SCAN1}, on)\nCFLAGS += -DDEBUG_SCAN1\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_SCAN1}, 1)\nCFLAGS += -DDEBUG_SCAN1\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_SCAN2}, on)\nCFLAGS += -DDEBUG_SCAN2\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_SCAN2}, 1)\nCFLAGS += -DDEBUG_SCAN2\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_EMIT}, on)\nCFLAGS += -DDEBUG_EMIT\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_EMIT}, 1)\nCFLAGS += -DDEBUG_EMIT\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_VM}, on)\nCFLAGS += -DDEBUG_VM\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_VM}, 1)\nCFLAGS += -DDEBUG_VM\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_INSTR}, on)\nCFLAGS += -DDEBUG_INSTR\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_INSTR}, 1)\nCFLAGS += -DDEBUG_INSTR\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_SHREDULER}, on)\nCFLAGS += -DDEBUG_SHREDULER\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_SHREDULER}, 1)\nCFLAGS += -DDEBUG_SHREDULER\nendif\n"  >> Makefile
-printf "ifeq (\${DEBUG_STACK}, on)\nCFLAGS += -DDEBUG_STACK\nendif\n" >> Makefile
-printf "ifeq (\${DEBUG_STACK}, 1)\nCFLAGS += -DDEBUG_STACK\nendif\n"  >> Makefile
-echo -e "\n# add soundpipe" >> Makefile
+printf "\n# handle debug\n" >> Makefile
+for iter in compile:off operator:off type:off scan0:off scan1:off scan2:off emit:off vm:off instr:off shreduler:off stack:off
+do
+	key=$(echo "$iter" | cut -d ':' -f 1)
+	val=$(echo "$iter" | cut -d ':' -f 2)
+	lib=$(echo "$iter" | cut -d ':' -f 4)
+	arg="_arg_debug_$key"
+	echo "DEBUG_${key~~} ?= ${!arg}"
+done >> Makefile
+
+# initialize source lists
+printf "\n# initialize source lists\n" >> Makefile
+for iter in core lang ugen eval
+do
+	echo "${iter}_src := \$(wildcard ${iter}/*.c)"
+done >> Makefile
+echo "drvr_src := drvr/driver.c" >> Makefile
+
+# add libraries
+printf "\n# add libraries\n" >> Makefile
+for iter in dummy:on:: spa:on:: sndfile:on:'/usr/include','/usr/local/include':-lsndfile alsa:on::-lasound jack:off::-ljack portaudio:off::-lportaudio soundio:off::-lsoundio
+do
+	key=$(echo "$iter" | cut -d ':' -f 1)
+	val=$(echo "$iter" | cut -d ':' -f 2)
+	lib=$(echo "$iter" | cut -d ':' -f 4)
+	if [ "${val}" = "on" ]
+	then val=1
+	else val=0
+	fi
+	[ -z "$lib" ] && printf "ifeq (\${%s_D}, on)\\nCFLAGS += -DHAVE_%s\\ndrvr_src += drvr/%s.c\\nelse ifeq (\${%s_D}, 1)\\nCFLAGS +=-DHAVE_%s\\ndrvr_src +=drvr/%s.c\\nendif\\n" "${key~~}" "${key~~}" "${key}" "${key~~}" "${key~~}" "${key}"
+	[ -z "$lib" ] || printf "ifeq (\${%s_D}, on)\\nLDFLAGS += %s\\nCFLAGS += -DHAVE_%s\\ndrvr_src += drvr/%s.c\\nelse ifeq (\${%s_D}, 1)\\nLDFLAGS += %s\\nCFLAGS +=-DHAVE_%s\\ndrvr_src +=drvr/%s.c\\nendif\\n" "${key~~}" "${lib}" "${key~~}" "${key}" "${key~~}" "${lib}" "${key~~}" "${key}"
+	done >> Makefile
+
+# add boolean
+printf "\n# add boolean\n" >> Makefile
+for iter in double:off coverage:off memcheck:off
+do
+	key=$(echo "$iter" | cut -d ':' -f 1)
+	val=$(echo "$iter" | cut -d ':' -f 2)
+	lib=$(echo "$iter" | cut -d ':' -f 4)
+	if [ "${val}" = "on" ]
+then [ "$key" = "double" ] && val=double;
+else [ "$key" = "double" ] && val=float;
+fi
+[ "$key" = "memcheck" ] && printf "ifeq (\${USE_%s}, on)\\nCFLAGS += -g\\nelse " "${key~~}"
+[ "$key" = "memcheck" ] && printf "ifeq (\${USE_%s}, 1)\\nCFLAGS += -g\\nendif\n" "${key~~}"
+[ "$key" = "coverage" ] && printf "ifeq (\${USE_%s}, on)\\nCFLAGS += -ftest-coverage -fprofile-arcs\\nelse " "${key~~}"
+[ "$key" = "coverage" ] && printf "ifeq (\${USE_%s}, 1)\\nCFLAGS += -ftest-coverage -fprofile-arcs\\nendif\n" "${key~~}"
+[ "$key" = "coverage" ] && printf "ifeq (\${USE_%s}, on)\\nLDFLAGS += --coverage\nelse " "${key~~}"
+[ "$key" = "coverage" ] && printf "ifeq (\${USE_%s}, 1)\\nLDFLAGS += --coverage\nendif\n" "${key~~}"
+done >> Makefile
+key="double"
+printf "ifeq (\${USE_%s}, on)\\nCFLAGS += -DUSE_%s} -DSPFLOAT=double\\nelse ifeq (\${USE_%s}, 1)\\nCFLAGS +=-DUSE_%s -DSPFLOAT=double\\nelse\\nCFLAGS+=-DSPFLOAT=float\\nendif\\n" "${key~~}" "${key~~}" "${key~~}" "${key~~}" >> Makefile
+
+# add definitions
+printf "\n# add definitions\n" >> Makefile
+d_func=d_func
+for iter in $d_func
+
+do
+	key=$(echo "$iter" | cut -d ':' -f 1)
+	val=$(echo "$iter" | cut -d ':' -f 2)
+	lib=$(echo "$iter" | cut -d ':' -f 4)
+	echo "CFLAGS+= -D${key~~}=\${${key~~}}"
+done >> Makefile
+
+# add directories
+printf "\n# add directories\n" >> Makefile
+for iter in api doc tag tok add
+do
+	printf "CFLAGS+=-DGWION_%s_DIR=\\\\\\\"\${GWION_%s_DIR}\\\\\\\"\n" "${iter~~}" "${iter~~}"
+done >> Makefile
+
+# add debug flags
+printf "\n# add debug flags\n" >> Makefile
+for iter in compile operator type scan0 scan1 scan2 emit vm instr shreduler stack
+do
+	printf "ifeq (\${DEBUG_%s}, on)\nCFLAGS += -DDEBUG_%s\nelse " "${iter~~}" "${iter~~}"
+	printf "ifeq (\${DEBUG_%s},  1)\nCFLAGS += -DDEBUG_%s\nendif\n" "${iter~~}" "${iter~~}"
+done >> Makefile
+
+# add soundpipe
+printf "\n# add soundpipe\n" >> Makefile
 echo "LDFLAGS+=${SOUNDPIPE_LIB}" >> Makefile
 echo "CFLAGS+=${SOUNDPIPE_INC}"  >> Makefile
-# initialize object lists
-echo '' >> Makefile
-echo '# initialize object lists' >> Makefile
-for tgt in "core" "lang" "ugen" "drvr" "eval"
-do echo "${tgt}_obj := \$(${tgt}_src:.c=.o)" >> Makefile
-done
 
+# initialize object lists
+printf "\n# initialize object lists\n" >> Makefile
+for iter in core lang ugen eval drvr
+do
+	echo "${iter}_obj := \$(${iter}_src:.c=.o)"
+done >> Makefile
 ###########
 # recipes #
 ###########
