Few fixes.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -87,8 +87,8 @@ die()
 : "${_arg_coverage:=$USE_COVERAGE}"
 : "${USE_MEMCHECK:=off}"
 : "${_arg_memcheck:=$USE_MEMCHECK}"
-: "${D_FUNC:=dummy_driver}"
-: "${_arg_d_func:=D_FUNC}"
+: "${D_FUNC:=dummy}"
+: "${_arg_d_func:=$D_FUNC}"
 : "${DUMMY_D:=on}"
 : "${_arg_dummy:=$DUMMY_D}"
 : "${DUMMY_INC:=}"
@@ -609,9 +609,9 @@ set -e
 # remove Makefile
 [ -f Makefile  ] && rm Makefile
 
-# test valid d_func
+# check default driver
 VALID_DRIVER=" dummy spa sndfile alsa jack portaudio soundio"
-grep "$_arg_d_func" <<<  "$VALID_DRIVER" || { echo "invalid default driver";exit 1; }
+grep "$_arg_d_func" <<<  "$VALID_DRIVER" > /dev/null || { echo "invalid default driver";exit 1; }
 
 if [ "$_arg_double" = "on" ]; then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
 if [ "$_arg_double" = "1"  ];then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
@@ -619,13 +619,8 @@ if [ "$_arg_double" = "1"  ];then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
 if [ "$USE_COVERAGE" = "1"  ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
 if [ "$USE_COVERAGE" = "on" ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
 if [ "$_arg_soundpipe_inc" ]; then _CFLAGS+=" $_arg_soundpipe_inc";fi
-echo "$_arg_cc -Iinclude -DDEBUG $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)"
 $_arg_cc -Iinclude -DDEBUG $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)
-echo generate header
 ./util/generate_header || exit 1
-echo generate soundpipe wrapper
-[ -d "$_arg_data" ] || exit 1 
-lua util/import.lua "$_arg_data" > ugen/soundpipe.c || exit 1
 {
 echo "PRG ?= ${_arg_prg}"
 echo "CC ?= ${_arg_cc}"
