Build system.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -50,7 +50,7 @@
 # ARG_HELP([The general script's help msg])
 # ARGBASH_GO()
 # needed because of Argbash --> m4_ignore([
-### START OF CODE GENERATED BY Argbash v2.3.0 one line above ###
+### START OF CODE GENERATED BY Argbash v2.4.0 one line above ###
 # Argbash is a bash code generator used to get arguments parsing right.
 # Argbash is FREE SOFTWARE, see https://argbash.io for more info
 
@@ -62,6 +62,16 @@ die()
 	echo "$1" >&2
 	exit ${_ret}
 }
+
+begins_with_short_option()
+{
+	local first_option all_short_options
+	all_short_options='h'
+	first_option="${1:0:1}"
+	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
+}
+
+
 
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 : "${PRG:="gwion"}"
@@ -575,7 +585,7 @@ do
 			_arg_debug_stack="on"
 			test "${1:0:5}" = "--no-" && _arg_debug_stack="off"
 			;;
-		-h|--help)
+		-h*|--help)
 			print_help
 			exit 0
 			;;
@@ -605,7 +615,7 @@ if [ "$_arg_double" = "1"  ];then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
 if [ "$USE_COVERAGE" = "1"  ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
 if [ "$USE_COVERAGE" = "on" ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
 if [ "$_arg_soundpipe_inc" ]; then _CFLAGS+=" $_arg_soundpipe_inc";fi
-$_arg_cc -Iinclude -DDEBUG $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)
+$_arg_cc -Iinclude -DDEBUG $_CFLAGS ${_arg_soundpipe_inc} util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)
 ./util/generate_header || exit 1
 {
 echo "PRG ?= ${_arg_prg}"
