Some clean.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -609,7 +609,9 @@ set -e
 if [ "$_arg_double" = "on" ]; then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
 if [ "$_arg_double" = "1"  ];then _CFLAGS+=" -DUSE_DOUBLE -DSPFLOAT=double";fi
 ([ "$_arg_double" = "on" ] || [ "$_arg_double" = "1"  ]) || _CFLAGS+=" -DSPFLOAT=float"
-$_arg_cc -ftest-coverage -fprofile-arcs --coverage -Iinclude $_arg_soundpipe_inc -DDEBUG $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)
+if [ "" = "1"  ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
+if [ "" = "on" ]; then _CFLAGS+=" -ftest-coverage -fprofile-arcs --coverage";fi
+$_arg_cc -Iinclude $_arg_soundpipe_inc -DDEBUG $_CFLAGS util/generate_header.c core/err_msg.c -o util/generate_header || (echo 'invalid compilation options'; exit 1;)
 echo generate header
 ./util/generate_header || exit 1
 echo generate soundpipe wrapper
